### ISSUE TITLE
Will it be modified to allow for reuse tables?

### ISSUE THREAD

**Issue by MacBoy** [mamaral/Organic#2]
This is nice!  Much simpler, without all the overhead.

For a scrolling list of cells, we will need to specify a reuseIdentifier.

Are there plans for reuse of the table cells?

Thank you for sharing! :-)

**Comment by mamaral** [comment]
Thanks! Yes indeed! I already have a working version now on a branch I've yet to push up, but want to clean it up to be easier to use. As it currently stands, you'll be able to reuse cells within a section. I'm thinking there will be an initializer for a section that essentially has a cellForRowAtIndexPath block where you can customize the cells based on the row, like you normally would. Thinking about all of the repercussions and edge cases now, but will get something in today hopefully! BTW, how did you find this repo?

**Comment by MacBoy** [comment]
Found the repo via the ManiacDev.com web site. I subscribe to their updates, which happen twice or thrice a week.

Here is the particular listing you are interested in:

https://maniacdev.com/2015/01/open-source-ios-library-that-simplifies-the-creation-of-complex-table-view-layouts

Looking forward to the updates you have described!  No urgency, take your time to ponder and breathe :-)

Thank you!

**Comment by mamaral** [comment]
Should be all set to handle reuse on a per-section basis. Take a look at what I just merged, https://github.com/mamaral/Organic/pull/3 or the updated README if you want more details. Feedback is always welcomed!

**Comment by mamaral** [comment]
I'm going to close this for now, let me know if you have any feedback!
