### ISSUE TITLE
Does it have Xib support?

### ISSUE THREAD

**Issue by faizmokh** [mamaral/Organic#7]
As per title, can Organic be used with xib files? I've tried to add my cells that have been created with xib but it doesn't show up in the tableview.

**Comment by mamaral** [comment]
I've never used it with xibs, but AFAIK it should work. Can you show any relevant code?

**Comment by faizmokh** [comment]
I see. Anyway, here's the snippets of my code.

```
- (void)viewWillAppear:(BOOL)animated {
    [self viewWillAppear:animated];

    SLCheckoutHeaderCell *headerCell = [[SLCheckoutHeaderCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"SLItemHeader"];
    headerCell.textLabel = @"Lorem ipsum";

    OrganicSection *headerSection = [OrganicSection sectionWithHeaderTitle:@"Profile" cells:@[headerCell]];

    ....

    self.sections = @[headerSection];
}
```

FYI, `SLCheckoutHeaderCell` is a subclass of `OrganicCell` and I've set the corresponding xib file identifier  to `SLItemHeader`. It does show the section title `Profile` though so I guess, I may have called the cell wrongly.

**Comment by mamaral** [comment]
Did you connect the subviews on your xib file as `IBOutlet`s in your `SLCheckoutHeaderCell`?

**Comment by faizmokh** [comment]
Yes, I do link each of the subviews to the `IBOutlets`.

**Comment by mamaral** [comment]
Hmmm I have an idea I'll test out and get back to you.

**Comment by jlaws** [comment]
It does work with Xib's, just make sure you register your nib in viewDidLoad

``` swift
    self.tableView?.registerNib(nib, forCellReuseIdentifier: MyCellIdentifier)
```

then when you use the reuse section get the cell like this

``` swift
    let cell = tableView.dequeueReusableCellWithIdentifier(MyCellIdentifier)
```

just make sure you nib subclasses OrganicCell
